# Generated by Django 3.2.4 on 2022-03-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile_picure',
            new_name='profile_picture',
        ),
    ]
